apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: surajhub-ingress
  namespace: surajhub
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - surajhub.example.com
    secretName: surajhub-tls
  rules:
  - host: surajhub.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: surajhub-service
            port:
              number: 80
