apiVersion: v1
kind: Secret
metadata:
  name: surajhub-secrets
  namespace: surajhub
type: Opaque
stringData:
  database-url: "postgresql://user:password@postgres-service:5432/surajhub"
  session-secret: "your-session-secret-min-32-chars-change-in-production"
  stripe-secret-key: "sk_live_YOUR_STRIPE_SECRET_KEY"
